version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch-browsers-legacy
    working_directory: ~/core-chopper
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install libpcsclite1 libpcsclite-dev libudev-dev
            npm install --quiet
      - run:
          name: Lint
          command:
            npm run lint
      - run:
          name: Build
          command:
            npm run build
      - save_cache:
          paths:
            - node_modules
          key: npm-dependency-cache-{{ checksum "package-lock.json" }}